### ISSUE TITLE
Support for newest InteliJ builds

### ISSUE THREAD

**Issue by EnragedIceberg** [jaredkhan/IntelliJEvaluateArithmetic#1]
This plugin looks great but I tried to install on 2020.1 and it doesn't show up in the plugin list.

I belive this is because it is not available for 2020.1 releases.

![image](https://user-images.githubusercontent.com/62996112/79434328-20dfa000-7fc6-11ea-9ea0-7369847b02eb.png)

Are you able to increase support for the newest InteliJ builds please.

**Comment by jaredkhan** [comment]
Hey @savill2020 👋 The plugin is now available on the 2020.1 platform

https://plugins.jetbrains.com/plugin/13778-evaluate-arithmetic
