### ISSUE TITLE
No ‘Evaluate Math Expressions’ in ‘Find Action’

### ISSUE THREAD

**Issue by Guerio** [jaredkhan/IntelliJEvaluateArithmetic#3]
![is](https://user-images.githubusercontent.com/37111423/80588034-2919ef80-8a4a-11ea-8da7-972874181845.png)

**Comment by jaredkhan** [comment]
@Guerio The action will only appear if you have some text selected. Do you?

**Comment by Guerio** [comment]
> @Guerio The action will only appear if you have some text selected. Do you?

The problem is solved.  I got  v1.3.0. Thank you very much for your plugin.
